#!/bin/sh

function usage() {
   cat << HEREDOC

   Usage:
      ocuser add [username]
      ocuser list
      ocuser remove [username]

HEREDOC
}

function add_user() {
    
    if [ $# -ne 1 ]; then
        usage
    fi

    certtool --generate-privkey --outfile /etc/pki/ocserv/private/$1.key
    cat << EOF > user.tmpl
cn = "AnyConnect VPN User"
unit = "admins"
expiration_days = 365
signing_key
tls_www_client
EOF
    certtool --generate-certificate --load-privkey /etc/pki/ocserv/private/$1.key --load-ca-certificate /etc/pki/ocserv/cacerts/ca.crt --load-ca-privkey /etc/pki/ocserv/cacerts/ca.key --template user.tmpl --outfile /etc/pki/ocserv/public/$1.crt
    certtool --to-p12 --load-privkey /etc/pki/ocserv/private/$1.key --pkcs-cipher 3des-pkcs12 --load-certificate /etc/pki/ocserv/public/$1.crt --outfile /tmp/user.p12 --outder

    cat /tmp/$1.p12
}

function list_users() {
    echo "Not implemented."
}

function remove_user() {
    echo "Not implemented."
}

function main() {

    if [ $# -lt 1 ]; then
        usage
        exit 1
    fi

    case $1 in
        add)
            shift
            add_user $@
            ;;
        list)
            list_users
            ;;
        remove)
            shift
            remove_user $@
            ;;
    esac
}

main "$@"
